# Generated by Django 3.2.13 on 2022-07-13 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0002_auto_20220713_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('carte_annonce', models.FileField(blank=True, null=True, upload_to='carte_annonces/')),
                ('fare_part', models.FileField(blank=True, null=True, upload_to='faire_parts/')),
                ('programme', models.TextField(null=True, verbose_name='PROGRAMME')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonce_catégorie', to='parametres.evenement')),
                ('participant', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'ANNONCES',
                'ordering': ['-add_le', '-update_le'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('created_le', models.DateTimeField(auto_now_add=True)),
                ('updated_le', models.DateTimeField(auto_now=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'MESSAGES',
                'ordering': ['-created_le', '-updated_le'],
            },
        ),
    ]
